trigger:
- master
pool:
  myTestVm
jobs:
- job: ParallelA
  steps:
  - bash: sleep 25
    displayName: 'Sleep for 25 seconds'
  - bash: echo Hello from parallel job A
    displayName: 'Run a one-line script'
- job: ParallelB
  steps:
  - bash: sleep 20
    displayName: 'Sleep for 20seconds'
  - bash: echo Hello from parallel job B
    displayName: 'Run a one-line script'
- job: Final
  dependsOn:
  - ParallelA
  - ParallelB
  steps:
  - script: echo Hello from final job
    displayName: 'Run a one-line script'